services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"

  monitor:
    build: .
    depends_on:
      - web
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus    